# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sorteio_pb2 as sorteio__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in sorteio_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SorteioServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SolicitarNumero = channel.unary_unary(
                '/SorteioService/SolicitarNumero',
                request_serializer=sorteio__pb2.Empty.SerializeToString,
                response_deserializer=sorteio__pb2.NumeroResponse.FromString,
                _registered_method=True)
        self.SolicitarNumeros = channel.unary_unary(
                '/SorteioService/SolicitarNumeros',
                request_serializer=sorteio__pb2.SolicitarRequest.SerializeToString,
                response_deserializer=sorteio__pb2.SorteioResponse.FromString,
                _registered_method=True)
        self.ReiniciarOuEncerrar = channel.unary_unary(
                '/SorteioService/ReiniciarOuEncerrar',
                request_serializer=sorteio__pb2.OpcaoRequest.SerializeToString,
                response_deserializer=sorteio__pb2.RespostaFinal.FromString,
                _registered_method=True)


class SorteioServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SolicitarNumero(self, request, context):
        """Solicitar um número inicial
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SolicitarNumeros(self, request, context):
        """Solicitar números do sorteio
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReiniciarOuEncerrar(self, request, context):
        """Reiniciar o sorteio ou encerrar
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SorteioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SolicitarNumero': grpc.unary_unary_rpc_method_handler(
                    servicer.SolicitarNumero,
                    request_deserializer=sorteio__pb2.Empty.FromString,
                    response_serializer=sorteio__pb2.NumeroResponse.SerializeToString,
            ),
            'SolicitarNumeros': grpc.unary_unary_rpc_method_handler(
                    servicer.SolicitarNumeros,
                    request_deserializer=sorteio__pb2.SolicitarRequest.FromString,
                    response_serializer=sorteio__pb2.SorteioResponse.SerializeToString,
            ),
            'ReiniciarOuEncerrar': grpc.unary_unary_rpc_method_handler(
                    servicer.ReiniciarOuEncerrar,
                    request_deserializer=sorteio__pb2.OpcaoRequest.FromString,
                    response_serializer=sorteio__pb2.RespostaFinal.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SorteioService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('SorteioService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SorteioService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SolicitarNumero(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SorteioService/SolicitarNumero',
            sorteio__pb2.Empty.SerializeToString,
            sorteio__pb2.NumeroResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SolicitarNumeros(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SorteioService/SolicitarNumeros',
            sorteio__pb2.SolicitarRequest.SerializeToString,
            sorteio__pb2.SorteioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReiniciarOuEncerrar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SorteioService/ReiniciarOuEncerrar',
            sorteio__pb2.OpcaoRequest.SerializeToString,
            sorteio__pb2.RespostaFinal.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
